// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.10
// source: video.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VideoRpc_GetVideoListByUserId_FullMethodName = "/video.VideoRpc/GetVideoListByUserId"
	VideoRpc_VideoFeed_FullMethodName            = "/video.VideoRpc/VideoFeed"
	VideoRpc_PublishVideo_FullMethodName         = "/video.VideoRpc/PublishVideo"
	VideoRpc_GetUserVideoCount_FullMethodName    = "/video.VideoRpc/GetUserVideoCount"
	VideoRpc_GetVideoListInfo_FullMethodName     = "/video.VideoRpc/GetVideoListInfo"
	VideoRpc_GetAuthorId_FullMethodName          = "/video.VideoRpc/GetAuthorId"
)

// VideoRpcClient is the client API for VideoRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoRpcClient interface {
	GetVideoListByUserId(ctx context.Context, in *GetVideoListByUserIdRequest, opts ...grpc.CallOption) (*GetVideoListByUserIdResponse, error)
	VideoFeed(ctx context.Context, in *VideoFeedRequest, opts ...grpc.CallOption) (*VideoFeedResponse, error)
	PublishVideo(ctx context.Context, in *PublishVideoRequest, opts ...grpc.CallOption) (*PublishVideoResponse, error)
	GetUserVideoCount(ctx context.Context, in *GetUserVideoCountRequest, opts ...grpc.CallOption) (*GetUserVideoCountResponse, error)
	GetVideoListInfo(ctx context.Context, in *GetVideoListInfoRequest, opts ...grpc.CallOption) (*GetVideoListInfoResponse, error)
	GetAuthorId(ctx context.Context, in *GetAuthorIdRequest, opts ...grpc.CallOption) (*GetAuthorIdResponse, error)
}

type videoRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoRpcClient(cc grpc.ClientConnInterface) VideoRpcClient {
	return &videoRpcClient{cc}
}

func (c *videoRpcClient) GetVideoListByUserId(ctx context.Context, in *GetVideoListByUserIdRequest, opts ...grpc.CallOption) (*GetVideoListByUserIdResponse, error) {
	out := new(GetVideoListByUserIdResponse)
	err := c.cc.Invoke(ctx, VideoRpc_GetVideoListByUserId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoRpcClient) VideoFeed(ctx context.Context, in *VideoFeedRequest, opts ...grpc.CallOption) (*VideoFeedResponse, error) {
	out := new(VideoFeedResponse)
	err := c.cc.Invoke(ctx, VideoRpc_VideoFeed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoRpcClient) PublishVideo(ctx context.Context, in *PublishVideoRequest, opts ...grpc.CallOption) (*PublishVideoResponse, error) {
	out := new(PublishVideoResponse)
	err := c.cc.Invoke(ctx, VideoRpc_PublishVideo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoRpcClient) GetUserVideoCount(ctx context.Context, in *GetUserVideoCountRequest, opts ...grpc.CallOption) (*GetUserVideoCountResponse, error) {
	out := new(GetUserVideoCountResponse)
	err := c.cc.Invoke(ctx, VideoRpc_GetUserVideoCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoRpcClient) GetVideoListInfo(ctx context.Context, in *GetVideoListInfoRequest, opts ...grpc.CallOption) (*GetVideoListInfoResponse, error) {
	out := new(GetVideoListInfoResponse)
	err := c.cc.Invoke(ctx, VideoRpc_GetVideoListInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoRpcClient) GetAuthorId(ctx context.Context, in *GetAuthorIdRequest, opts ...grpc.CallOption) (*GetAuthorIdResponse, error) {
	out := new(GetAuthorIdResponse)
	err := c.cc.Invoke(ctx, VideoRpc_GetAuthorId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoRpcServer is the server API for VideoRpc service.
// All implementations must embed UnimplementedVideoRpcServer
// for forward compatibility
type VideoRpcServer interface {
	GetVideoListByUserId(context.Context, *GetVideoListByUserIdRequest) (*GetVideoListByUserIdResponse, error)
	VideoFeed(context.Context, *VideoFeedRequest) (*VideoFeedResponse, error)
	PublishVideo(context.Context, *PublishVideoRequest) (*PublishVideoResponse, error)
	GetUserVideoCount(context.Context, *GetUserVideoCountRequest) (*GetUserVideoCountResponse, error)
	GetVideoListInfo(context.Context, *GetVideoListInfoRequest) (*GetVideoListInfoResponse, error)
	GetAuthorId(context.Context, *GetAuthorIdRequest) (*GetAuthorIdResponse, error)
	mustEmbedUnimplementedVideoRpcServer()
}

// UnimplementedVideoRpcServer must be embedded to have forward compatible implementations.
type UnimplementedVideoRpcServer struct {
}

func (UnimplementedVideoRpcServer) GetVideoListByUserId(context.Context, *GetVideoListByUserIdRequest) (*GetVideoListByUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoListByUserId not implemented")
}
func (UnimplementedVideoRpcServer) VideoFeed(context.Context, *VideoFeedRequest) (*VideoFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VideoFeed not implemented")
}
func (UnimplementedVideoRpcServer) PublishVideo(context.Context, *PublishVideoRequest) (*PublishVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishVideo not implemented")
}
func (UnimplementedVideoRpcServer) GetUserVideoCount(context.Context, *GetUserVideoCountRequest) (*GetUserVideoCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserVideoCount not implemented")
}
func (UnimplementedVideoRpcServer) GetVideoListInfo(context.Context, *GetVideoListInfoRequest) (*GetVideoListInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoListInfo not implemented")
}
func (UnimplementedVideoRpcServer) GetAuthorId(context.Context, *GetAuthorIdRequest) (*GetAuthorIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthorId not implemented")
}
func (UnimplementedVideoRpcServer) mustEmbedUnimplementedVideoRpcServer() {}

// UnsafeVideoRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoRpcServer will
// result in compilation errors.
type UnsafeVideoRpcServer interface {
	mustEmbedUnimplementedVideoRpcServer()
}

func RegisterVideoRpcServer(s grpc.ServiceRegistrar, srv VideoRpcServer) {
	s.RegisterService(&VideoRpc_ServiceDesc, srv)
}

func _VideoRpc_GetVideoListByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoListByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoRpcServer).GetVideoListByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoRpc_GetVideoListByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoRpcServer).GetVideoListByUserId(ctx, req.(*GetVideoListByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoRpc_VideoFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoRpcServer).VideoFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoRpc_VideoFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoRpcServer).VideoFeed(ctx, req.(*VideoFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoRpc_PublishVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoRpcServer).PublishVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoRpc_PublishVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoRpcServer).PublishVideo(ctx, req.(*PublishVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoRpc_GetUserVideoCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserVideoCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoRpcServer).GetUserVideoCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoRpc_GetUserVideoCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoRpcServer).GetUserVideoCount(ctx, req.(*GetUserVideoCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoRpc_GetVideoListInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoListInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoRpcServer).GetVideoListInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoRpc_GetVideoListInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoRpcServer).GetVideoListInfo(ctx, req.(*GetVideoListInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoRpc_GetAuthorId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoRpcServer).GetAuthorId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoRpc_GetAuthorId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoRpcServer).GetAuthorId(ctx, req.(*GetAuthorIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoRpc_ServiceDesc is the grpc.ServiceDesc for VideoRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video.VideoRpc",
	HandlerType: (*VideoRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVideoListByUserId",
			Handler:    _VideoRpc_GetVideoListByUserId_Handler,
		},
		{
			MethodName: "VideoFeed",
			Handler:    _VideoRpc_VideoFeed_Handler,
		},
		{
			MethodName: "PublishVideo",
			Handler:    _VideoRpc_PublishVideo_Handler,
		},
		{
			MethodName: "GetUserVideoCount",
			Handler:    _VideoRpc_GetUserVideoCount_Handler,
		},
		{
			MethodName: "GetVideoListInfo",
			Handler:    _VideoRpc_GetVideoListInfo_Handler,
		},
		{
			MethodName: "GetAuthorId",
			Handler:    _VideoRpc_GetAuthorId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "video.proto",
}
