// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"kitkot/server/apis/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/douyin/user/register",
				Handler: UserRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/douyin/user/login",
				Handler: UserLoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/douyin/user",
					Handler: UserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/douyin/publish/action",
					Handler: VideoActionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/douyin/comment/action",
					Handler: CommentActionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/comment/list",
					Handler: CommentListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/douyin/message/action",
					Handler: MessageActionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/message/chat",
					Handler: MessageChatHandler(serverCtx),
				},
			}...,
		),
	)
}
